language: python
matrix:
  include:
  - python: 3.6
    env: TOXENV=py36
  - python: 3.5
    env: TOXENV=py35
  - python: 3.4
    env: TOXENV=py34
  - python: 2.7
    env: TOXENV=py27
  - python: 3.6
    env: TOXENV=flake8
  - python: 3.6
    env: TOXENV=isort
install: pip install -U tox
script: tox -e ${TOXENV}
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  skip_upload_docs: true
  user: jarshwah
  password:
    secure: eSh3cxP7hkuviWTgBbuxVWLKOqD49v8Yxty9TPWSux7iRkt6mxE7KXbTkI4F7hhghu9yzAFqDpNFh4SIxsoZlDHvOWBGEG/6qMMkykG963ke+WZeZekey7uldN672OID0PxRY8odIGuy3pOjtuhulopV5zsh83+9i5ZXN7WFtIdFOfBHFd2FFdHLmOiAhYdaC8Pb9pCvfPSR3Al8sEHUWwKuIo5Qd/Zqz8mnZjVZSZya+PmI2AFW4RhyCwBoxmRM/MlznQzbUa4crp63sj1WCaAmNH2gjWp/9uVphRQQ5x6tlHpasof7AdlZzpYygmU8ohS8cIWhAmlofLiy0TfDAwcSwqo+6yrogKQ1P+2q2DBz/UmPGRyR6EKOGdEJOpyfDivywii2wo79/5IPZ2Zzp+XUjCLjLUEIuewzE59SMXeE/kaxHI8hj9uyOPnYbWS28Q98sIUW1xELbTclDAR5S5sU2G05P2Yf7dmooI3KObf7iBqKIk9f2VgGTFjxKZNgd0nw38O6b7T38gMOQo1sY/Web3/0Qx7mDWh2oCVUhxNDnStGIEQqKNccN7ivkrLSs+n0Pt/LBP4qrrNhhiyN5k5qGJxJ60Ev1El/dXn6xMyK88Z+j6q3a4jNHwgddBHbuU2dHLP0ivhrJrDUOV+Z5kokcWQiV+wBVESx5z4020g=
  on:
    repo: jarshwah/flake8_formatter_abspath
    condition: "$TOXENV = py36"
    tags: true
